"""initial_schema_foundations

Revision ID: 6e764fc2c9d0
Revises: 
Create Date: 2026-09-28 21:52:26.682101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e764fc2c9d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_run_at'), ['run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('llm_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_cache_prompt_hash'), ['prompt_hash'], unique=True)

    op.create_table('papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('preset_type', sa.String(length=50), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_school_id'), ['school_id'], unique=False)

    op.create_table('remedial_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remedial_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remedial_plans_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedial_plans_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('schools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('board', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_schools_status'), ['status'], unique=False)

    op.create_table('syllabus_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('board', sa.String(length=50), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('chapter', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('syllabus_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_syllabus_nodes_board'), ['board'], unique=False)
        batch_op.create_index(batch_op.f('ix_syllabus_nodes_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_syllabus_nodes_class_level'), ['class_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_syllabus_nodes_subject_name'), ['subject_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_syllabus_nodes_topic'), ['topic'], unique=False)

    op.create_table('topic_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('chapter', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('correct_attempts', sa.Integer(), nullable=False),
    sa.Column('accuracy_percentage', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_stats_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_stats_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_stats_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_stats_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_stats_user_id'), ['user_id'], unique=False)

    op.create_table('weak_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('chapter', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('identified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weak_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weak_topics_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weak_topics_user_id'), ['user_id'], unique=False)

    op.create_table('paper_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('qid', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_items_paper_id'), ['paper_id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='uq_school_subject_code')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_school_id'), ['school_id'], unique=False)

    op.create_table('tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('proctoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tests_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_section_id'), ['section_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('school_code', sa.String(length=50), nullable=True),
    sa.Column('teacher_code', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_roll_number'), ['roll_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_school_code'), ['school_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_teacher_code'), ['teacher_code'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_test_id'), ['test_id'], unique=False)

    op.create_table('bookmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('qid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'qid', name='uq_user_bookmark')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmarks_qid'), ['qid'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_user_id'), ['user_id'], unique=False)

    op.create_table('collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_user_id'), ['user_id'], unique=False)

    op.create_table('favourites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('qid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'qid', name='uq_user_favourite')
    )
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourites_qid'), ['qid'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourites_user_id'), ['user_id'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('disclaimer_accepted', sa.Boolean(), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('incharges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('wing_name', sa.String(length=100), nullable=False),
    sa.Column('can_approve_teachers', sa.Boolean(), nullable=False),
    sa.Column('can_approve_students', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('incharges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incharges_school_id'), ['school_id'], unique=False)

    op.create_table('question_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('qid', sa.String(length=36), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_notes_qid'), ['qid'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_notes_user_id'), ['user_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('short_id', sa.String(length=20), nullable=False),
    sa.Column('long_id', sa.String(length=100), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('owner_teacher_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_long_id'), ['long_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_questions_owner_teacher_id'), ['owner_teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_short_id'), ['short_id'], unique=True)

    op.create_table('sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=50), nullable=False),
    sa.Column('class_teacher_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'class_level', 'section_name', name='uq_school_section')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_school_id'), ['school_id'], unique=False)

    op.create_table('attempt_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('qid', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('marks_awarded', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_answers_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.String(length=200), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_topic'), ['topic'], unique=False)

    op.create_table('collection_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('qid', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_items_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_items_qid'), ['qid'], unique=False)

    op.create_table('proctor_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_meta_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proctor_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proctor_events_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('question_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('qid', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['qid'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qid', 'version', name='uq_qid_version')
    )
    with op.batch_alter_table('question_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_versions_qid'), ['qid'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_versions_verification_status'), ['verification_status'], unique=False)

    op.create_table('student_enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by_id', sa.String(length=36), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_enrollments_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_enrollments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_enrollments_student_id'), ['student_id'], unique=False)

    op.create_table('teacher_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'section_id', 'subject_id', name='uq_teacher_section_subject')
    )
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_assignments_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('verification_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('qid', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('question_version_id', sa.String(length=36), nullable=False),
    sa.Column('run_no', sa.Integer(), nullable=False),
    sa.Column('solver_model', sa.String(length=100), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('agree', sa.Boolean(), nullable=False),
    sa.Column('diff_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_runs_qid'), ['qid'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_runs_question_version_id'), ['question_version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_runs_question_version_id'))
        batch_op.drop_index(batch_op.f('ix_verification_runs_qid'))

    op.drop_table('verification_runs')
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_subject_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_section_id'))

    op.drop_table('teacher_assignments')
    with op.batch_alter_table('student_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_enrollments_status'))
        batch_op.drop_index(batch_op.f('ix_student_enrollments_section_id'))

    op.drop_table('student_enrollments')
    with op.batch_alter_table('question_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_versions_verification_status'))
        batch_op.drop_index(batch_op.f('ix_question_versions_qid'))

    op.drop_table('question_versions')
    with op.batch_alter_table('proctor_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proctor_events_attempt_id'))

    op.drop_table('proctor_events')
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_items_qid'))
        batch_op.drop_index(batch_op.f('ix_collection_items_collection_id'))

    op.drop_table('collection_items')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_topic'))
        batch_op.drop_index(batch_op.f('ix_chunks_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_file_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_chapter'))

    op.drop_table('chunks')
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_answers_attempt_id'))

    op.drop_table('attempt_answers')
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_school_id'))

    op.drop_table('sections')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_short_id'))
        batch_op.drop_index(batch_op.f('ix_questions_school_id'))
        batch_op.drop_index(batch_op.f('ix_questions_owner_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_questions_long_id'))

    op.drop_table('questions')
    with op.batch_alter_table('question_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_question_notes_qid'))

    op.drop_table('question_notes')
    with op.batch_alter_table('incharges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incharges_school_id'))

    op.drop_table('incharges')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_files_status'))
        batch_op.drop_index(batch_op.f('ix_files_school_id'))

    op.drop_table('files')
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favourites_qid'))

    op.drop_table('favourites')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_user_id'))

    op.drop_table('collections')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmarks_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_qid'))

    op.drop_table('bookmarks')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_test_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_status'))

    op.drop_table('attempts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_teacher_code'))
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_school_id'))
        batch_op.drop_index(batch_op.f('ix_users_school_code'))
        batch_op.drop_index(batch_op.f('ix_users_roll_number'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tests_section_id'))
        batch_op.drop_index(batch_op.f('ix_tests_school_id'))
        batch_op.drop_index(batch_op.f('ix_tests_created_by_id'))

    op.drop_table('tests')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_school_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('paper_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_items_paper_id'))

    op.drop_table('paper_items')
    with op.batch_alter_table('weak_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weak_topics_user_id'))
        batch_op.drop_index(batch_op.f('ix_weak_topics_section_id'))

    op.drop_table('weak_topics')
    with op.batch_alter_table('topic_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_stats_user_id'))
        batch_op.drop_index(batch_op.f('ix_topic_stats_topic'))
        batch_op.drop_index(batch_op.f('ix_topic_stats_subject'))
        batch_op.drop_index(batch_op.f('ix_topic_stats_section_id'))
        batch_op.drop_index(batch_op.f('ix_topic_stats_chapter'))

    op.drop_table('topic_stats')
    with op.batch_alter_table('syllabus_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_syllabus_nodes_topic'))
        batch_op.drop_index(batch_op.f('ix_syllabus_nodes_subject_name'))
        batch_op.drop_index(batch_op.f('ix_syllabus_nodes_class_level'))
        batch_op.drop_index(batch_op.f('ix_syllabus_nodes_chapter'))
        batch_op.drop_index(batch_op.f('ix_syllabus_nodes_board'))

    op.drop_table('syllabus_nodes')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_status'))
        batch_op.drop_index(batch_op.f('ix_schools_code'))

    op.drop_table('schools')
    with op.batch_alter_table('remedial_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remedial_plans_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_remedial_plans_section_id'))

    op.drop_table('remedial_plans')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_school_id'))
        batch_op.drop_index(batch_op.f('ix_papers_created_by_id'))

    op.drop_table('papers')
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_cache_prompt_hash'))

    op.drop_table('llm_cache')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))

    op.drop_table('jobs')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
